export const mockData = {
  nodeList: [
    {
      netId: '01',
      credNodeNbr: '004',
      credNodeName: '客户取现额度',
      credNodeType: 'cash',
      credNodeDesc: '客户取现额度',
    },
    {
      netId: '01',
      credNodeNbr: '005',
      credNodeName: '客户现金分期额度',
      credNodeType: 'cashLoan',
      credNodeDesc: '客户现金分期额度',
    },
    {
      netId: '01',
      credNodeNbr: '017',
      credNodeName: '客户取现，现金管控',
      credNodeType: 'cc',
      credNodeDesc: '004,005管控节点',
    },
    {
      netId: '01',
      credNodeNbr: '001',
      credNodeName: '客户级循环信用额度',
      credNodeType: 'crlimt',
      credNodeDesc: '客户级循环信用额度',
    },
    {
      netId: '01',
      credNodeNbr: '003',
      credNodeName: '客户分期额度',
      credNodeType: 'loan',
      credNodeDesc: '客户分期额度',
    },
    {
      netId: '03',
      credNodeNbr: '002',
      credNodeName: '客户大额分期额度',
      credNodeType: 'splmt',
      credNodeDesc: '客户大额分期额度',
    },
    {
      netId: 'custNet4S',
      credNodeNbr: 'custNet4Ssplmt',
      credNodeName: 'custNet4Ssplmt',
      credNodeType: 'splmt',
      credNodeDesc: 'custNet4Ssplmt',
    },
    {
      netId: 'custNet4T',
      credNodeNbr: 'custNet4Tcash',
      credNodeName: 'custNet4Tcash',
      credNodeType: 'cash',
      credNodeDesc: 'custNet4Tcash',
    },
    {
      netId: 'custNet4T',
      credNodeNbr: 'custNet4Tlimt',
      credNodeName: 'custNet4Tlimt',
      credNodeType: 'crlimt',
      credNodeDesc: 'custNet4Tlimt',
    },
    {
      netId: 'custNet4T',
      credNodeNbr: 'custNet4Tloan',
      credNodeName: 'custNet4Tloan',
      credNodeType: 'loan',
      credNodeDesc: 'custNet4Tloan',
    },
  ],
  meshList: [
    {
      netId: '01',
      credNodeNbr: '004',
      relatNodeNbr: '001',
      relatType: '1',
      relatDesc: '占比',
    },
    {
      netId: '01',
      credNodeNbr: '004',
      relatNodeNbr: '017',
      relatType: '0',
      relatDesc: '客户取现额度--客户取现现金分期管控',
    },
    {
      netId: '01',
      credNodeNbr: '005',
      relatNodeNbr: '001',
      relatType: '0',
      relatDesc: '客户现金分期--客户级循环信用额度',
    },
    {
      netId: '01',
      credNodeNbr: '005',
      relatNodeNbr: '001',
      relatType: '1',
      relatDesc: '占比',
    },
    {
      netId: '01',
      credNodeNbr: '005',
      relatNodeNbr: '017',
      relatType: '0',
      relatDesc: '客户现金分期--客户级循环信用额度',
    },
    {
      netId: '01',
      credNodeNbr: '003',
      relatNodeNbr: '001',
      relatType: '0',
      relatDesc: '客户分期额度--客户级循环信用额度',
    },
    {
      netId: '01',
      credNodeNbr: '003',
      relatNodeNbr: '001',
      relatType: '1',
      relatDesc: '占比',
    },
    {
      netId: 'custNet4T',
      credNodeNbr: 'custNet4Tcash',
      relatNodeNbr: 'custNet4Tlimt',
      relatType: '0',
      relatDesc: '',
    },
    {
      netId: 'custNet4T',
      credNodeNbr: 'custNet4Tcash',
      relatNodeNbr: 'custNet4Tlimt',
      relatType: '1',
      relatDesc: '',
    },
    {
      netId: 'custNet4T',
      credNodeNbr: 'custNet4Tcash',
      relatNodeNbr: 'custNet4Tlimt',
      relatType: '0',
      relatDesc: '',
    },
    {
      netId: 'custNet4T',
      credNodeNbr: 'custNet4Tloan',
      relatNodeNbr: 'custNet4Tlimt',
      relatType: '0',
      relatDesc: '',
    },
  ],
}
